app:
  name: journals


org:
  caringbridge:
    services:
      db:
        dbname: ${mongoDb:CB}
        host: ${mongoHost:development.caringbridge.org}
        port: ${mongoPort:27017}
        username: ${mongoUser:}
        password: ${mongoPwd:}
      version: 1.0
      swagger:
        title: CaringBridge Journals Micro-Service
        description: >
          The journal service returns paginated lists of journal entry summaries and detailed journal entries
        uri-base: /journals  # Tried using ${app.name} here without success, not sure why
        termslocation: /terms_of_service.txt
        contact: contact@caringbridge.org
        license:
          type: Caring Bridge proprietary license
          url: http://www.caringbridge.org/licenses/LICENSE

#Enable only health of spring boot actuator
endpoints:
  beans:
    enabled: false
  configprops:
    enabled: false
  docs:
    enabled: false
  dump:
    enabled: false
  env:
    enabled: false
  flyway:
    enabled: false
  health:
    id: health
  info:
    enabled: false
  jmx:
    enabled: false
  jolokia:
    enabled: false
  liquibase:
    enabled: false
  logfile:
    enabled: false
  mappings:
    enabled: false
  metrics:
    enabled: false
  shutdown:
    enabled: false
  trace:
    enabled: false


spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

server:
  port: 11000

---
spring:
  profiles: qa

server:
  port: 11000
  undertow:
    accesslog:
      dir: /var/log/microservices/${app.name}
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %{i,X-Request-Id} %D'
