app:
  name: references
  

org:
  caringbridge:
    services:
      version: 1.0
      swagger:
        title: CaringBridge Reference Micro-Service
        description: >
          This is a multi-line description of
          the micro service. 
        uri-base: /references  # Tried using ${app.name} here without success, not sure why
        termslocation: /terms_of_service.txt
        contact: contact@caringbridge.org
        license:
          type: Caring Bridge proprietary license
          url: http://www.caringbridge.org/licenses/LICENSE

spring:
  profiles:
    active: dev
    
---
spring:
  profiles: dev

server:
  port: 11000

---
spring:
  profiles: qa
  
server:
  port: 11000
  undertow:
    accesslog:
      dir: /var/log/microservices/${app.name}
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %{i,X-Request-Id} %D'
 